# Generated by Django 5.1.3 on 2024-12-05 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('os_type', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_device_info',
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_device_user_id_34dd40_idx'), models.Index(fields=['ip_address'], name='user_device_ip_addr_67feb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('registration_source', models.CharField(default='web', max_length=50)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Email Verified'), ('expired', 'Verification Expired')], default='pending', max_length=20)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_registration_info',
                'indexes': [models.Index(fields=['registration_status'], name='user_regist_registr_5dd687_idx'), models.Index(fields=['registered_at'], name='user_regist_registe_bd1ce6_idx')],
            },
        ),
    ]
